name: release

on:
  push:
    tags:
      - '**'

jobs:
  build:
    name: Create a release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create release
        uses: actions/create-release@latest
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: Liaison CS Config Factory ${{ github.ref }}
          draft: false
          prerelease: false
